In [1]:
import torch

## Creating tensors

In [15]:
x = torch.rand(2,3, dtype=torch.float16) #empty, zeros, rand, randn
print(x)
print(x.size())

tensor([[0.3789, 0.0825, 0.1836],
        [0.5200, 0.9229, 0.3208]], dtype=torch.float16)
torch.Size([2, 3])


In [17]:
#create tensor from python list

x = torch.tensor([2.5,0.1])
x= print(x)

tensor([2.5000, 0.1000])


## Simple tensor ops

In [ ]:
#simple tensor ops

x= torch.rand(2,2)
y = torch.rand(2,2)

print(x,y)

add_res = x + y
print(add_res)

add_res = torch.add(x,y)
print(add_res)

#in-place add

y.add_(x)
print(y)

tensor([[0.1479, 0.7279],
        [0.6596, 0.1003]]) tensor([[0.2104, 0.9980],
        [0.0894, 0.1506]])
tensor([[0.3583, 1.7259],
        [0.7489, 0.2508]])
tensor([[0.3583, 1.7259],
        [0.7489, 0.2508]])
tensor([[0.3583, 1.7259],
        [0.7489, 0.2508]])


In pytorch, any function with trailing underscore (add_) means it does the operation 'in-place'

## Slicing Ops

In [22]:
x = torch.rand(5,3)
print(x)

tensor([[0.8422, 0.9703, 0.6777],
        [0.2605, 0.9652, 0.4723],
        [0.4313, 0.7628, 0.9278],
        [0.9244, 0.5734, 0.8736],
        [0.3428, 0.9730, 0.1763]])


In [ ]:
#slicing
print(x[:,0]) #all rows, but only col 0

tensor([0.8422, 0.2605, 0.4313, 0.9244, 0.3428])


In [26]:
print(x[1,:]) #only second row (1) and all cols

tensor([0.2605, 0.9652, 0.4723])


In [ ]:
print(x[2,2]) #get tensor at 3rd row (2) and 3rd col (2)

tensor(0.9278)


In [29]:
print(x[2,2].item()) #get actual value of tensor at 3rd row (2) and 3rd col (2)

# You can use this only if you have one elem in the tensor

0.9277931451797485


## Reshaping tensors

In [30]:
x = torch.rand(4,4)
print(x)

tensor([[0.7767, 0.8079, 0.4334, 0.9469],
        [0.7093, 0.1610, 0.0986, 0.1724],
        [0.7639, 0.9600, 0.7607, 0.8821],
        [0.8902, 0.2637, 0.4216, 0.3189]])


In [33]:
y = x.view(16) #1d tensor of 16
print(y)

tensor([0.7767, 0.8079, 0.4334, 0.9469, 0.7093, 0.1610, 0.0986, 0.1724, 0.7639,
        0.9600, 0.7607, 0.8821, 0.8902, 0.2637, 0.4216, 0.3189])


In [35]:
y = x.view(-1,8) #Using -1 in a dim means you aren't passing any dim value for that dim. Torch automatically computes the right size based on other given dims
print(y) # creates a 2*8 tensor

tensor([[0.7767, 0.8079, 0.4334, 0.9469, 0.7093, 0.1610, 0.0986, 0.1724],
        [0.7639, 0.9600, 0.7607, 0.8821, 0.8902, 0.2637, 0.4216, 0.3189]])


In [36]:
y.size()

torch.Size([2, 8])

## Convert numpy arrs to torch tensors and vice verse

In [37]:
import numpy as np

In [46]:
 a = torch.ones(5)
 print(a)

tensor([1., 1., 1., 1., 1.])


In [47]:
b = a.numpy() #convert to np
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


One thing to be careful about is that b now always refer's to a's memory location. So any change to a, will reflect in b (See below)

In [48]:
a.add_(1) #adding 1 to all elements of tensor a
print(a)
print(b) #this will also add all 1s to numpyarr of a which is b

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [50]:
#numpy to tensor

a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b) 

#similar to before be careful as modifying a will also modify b

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


## Running torch and storing tensors on GPU (CUDA)

In [55]:
torch.cuda.is_available() #check if cuda available

False

In [56]:
if torch.cuda.is_available():
    device = torch.device("cuda") #define the device as cuda
    x = torch.ones(5, device=device) #create a tensor x on GPU
    y = torch.ones(5) #create on cpu and then move to GPU
    y = y.to(device)

#Note: you cannot convert to numpy if tensors are on GPU as numpy only works on CPU

## Requires Grad

This tells torch to store the gradient for the variable or tensor, such that later on in ML workflows, it can optimized.

In [58]:
x = torch.ones(5, requires_grad=True) #requires_grad is False by default
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
